[versions]
springBootVersion = "3.3.4"
lombokVersion = "1.18.34"

[libraries]
springBootStarterWeb = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "springBootVersion" }
lombok = { group = "org.projectlombok:lombok", name = "lombok", version.ref = "lombokVersion" }

[plugins]
springBoot = {id = "org.springframework.boot", version.ref ="springBootVersion"}
dependencyManagement = {id = "io.spring.dependency-management", version = "1.1.6"}